#LISTAS

#Definir una lista
lista=['a','b','c','d','e','f','g','h','i','j']

#Acceder a los elementos de una lista
#print(lista[2]) #output ??
#print(lista[-2])

#qué pasa si quiero el elemento que está por la mitad ?
#print(lista[int(len(lista)/2)])

#print(len(lista))

#SLICES
#print(lista[2:5])

#Modificar un elemento de la lista
#lista[0]=1
#print(lista)

#Insertar vs añadir elementos a una lista

lista.append('k')
print(lista)
#lista.insert(2,0)
#print(lista)



#Eliminar elementos de la lista: pop del remove




#sort vs sorted
nums=[4,36,9,1,4,34]

#nums=sorted(nums)
#print(nums)

#nums.sort()
#print(nums)




#¿QUÉ DIFERENCIA HAY ENTRE UNA LISTA Y UNA TUPLA ?
l=[1,2,3]
t=(1,2,3)

#las tuplas no se pueden modificar


#Indices con strings:
my_str='HOLA BUENOS DÍAS'
print(my_str[0])




#Hacer una copia de una lista



#len,max,min